// Projeto antigo/Front-end/src/screens/institution/MyRequests.tsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useApp } from "../../store/AppContext";

const tabs = ["Todas", "Abertas", "Aguardando", "Confirmadas", "Concluídas", "Canceladas"];

const statusMap: Record<string, { label: string; cls: string }> = {
  aberta: { label: "Buscando professor", cls: "bg-amber-100 text-amber-700" },
  aguardando: { label: "Aguardando confirmação", cls: "bg-blue-100 text-blue-700" },
  confirmada: { label: "Professor confirmado", cls: "bg-green-100 text-green-700" },
  recusada: { label: "Recusada", cls: "bg-red-100 text-red-600" },
  concluida: { label: "Concluída", cls: "bg-slate-100 text-slate-600" },
  cancelada: { label: "Cancelada", cls: "bg-red-100 text-red-500" },
};

const tabFilter: Record<string, string[]> = {
  Todas: [],
  Abertas: ["aberta"],
  Aguardando: ["aguardando"],
  Confirmadas: ["confirmada"],
  Concluídas: ["concluida"],
  Canceladas: ["cancelada"],
};

function fmt(data: string) {
  if (!data) return "—";
  const [y, m, d] = data.split("-");
  return `${d}/${m}/${y}`;
}

export default function MyRequests() {
  const navigate = useNavigate();
  const { requests, cancelRequest } = useApp();
  const [active, setActive] = useState("Todas");
  const [confirmCancel, setConfirmCancel] = useState<string | null>(null);

  const filtered = tabFilter[active].length > 0
    ? requests.filter((r) => tabFilter[active].includes(r.status))
    : requests;

  const handleCancel = (id: string) => {
    cancelRequest(id);
    setConfirmCancel(null);
  };

  return (
    <div className="p-8">
      <div className="flex items-start justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">Minhas solicitações</h1>
          <p className="text-sm text-slate-500 mt-1">Acompanhe todas as substituições solicitadas</p>
        </div>
        <button onClick={() => navigate("/instituicao/solicitar")} className="bg-blue-600 hover:bg-blue-700 text-white font-semibold px-5 py-2.5 rounded-xl text-sm transition-all flex items-center gap-2">
          <svg width="16" height="16" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clipRule="evenodd" /></svg>
          Nova solicitação
        </button>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 bg-slate-100 p-1 rounded-xl mb-6 overflow-x-auto">
        {tabs.map((tab) => {
          const count = tabFilter[tab].length > 0 ? requests.filter((r) => tabFilter[tab].includes(r.status)).length : requests.length;
          return (
            <button key={tab} onClick={() => setActive(tab)}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-all whitespace-nowrap ${active === tab ? "bg-white text-slate-800 shadow-sm" : "text-slate-500 hover:text-slate-700"}`}>
              {tab}
              {count > 0 && (
                <span className={`ml-1.5 text-xs font-semibold px-1.5 py-0.5 rounded-full ${active === tab ? "bg-blue-100 text-blue-700" : "bg-slate-200 text-slate-500"}`}>
                  {count}
                </span>
              )}
            </button>
          );
        })}
      </div>

      {filtered.length === 0 ? (
        <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-16 text-center">
          <div className="text-4xl mb-3">📭</div>
          <p className="font-semibold text-slate-700 mb-1">Nenhuma solicitação {active !== "Todas" ? active.toLowerCase() : "encontrada"}</p>
          {active === "Todas" && (
            <button onClick={() => navigate("/instituicao/solicitar")} className="mt-4 bg-blue-600 hover:bg-blue-700 text-white font-semibold px-5 py-2.5 rounded-xl text-sm transition-all">
              Criar primeira solicitação
            </button>
          )}
        </div>
      ) : (
        <div className="space-y-3">
          {filtered.map((r) => {
            const s = statusMap[r.status];
            return (
              <div key={r.id} className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5 hover:shadow-md transition-all">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1">
                    <div className="flex items-center gap-3 flex-wrap">
                      <h3 className="font-bold text-slate-800">{r.disciplina}</h3>
                      {r.turma && <span className="text-sm text-slate-500">· {r.turma}</span>}
                      <span className={`text-xs font-semibold px-2.5 py-1 rounded-full ${s.cls}`}>{s.label}</span>
                    </div>
                    <div className="flex items-center gap-4 mt-2 text-sm text-slate-500 flex-wrap">
                      <span>📅 {fmt(r.data)}</span>
                      <span>🕐 {r.horarioInicio} – {r.horarioFim}</span>
                      <span>{r.modalidade === "presencial" ? `🏫 ${r.cidade}` : "💻 Online"}</span>
                      <span>💰 R$ {r.valor}</span>
                    </div>
                    {r.professorConvidadoNome && (
                      <p className="text-sm text-slate-600 mt-2">
                        👩‍🏫 {r.status === "confirmada" ? "Confirmado:" : "Convidado:"}{" "}
                        <strong>{r.professorConvidadoNome}</strong>
                      </p>
                    )}
                  </div>
                  <div className="flex items-center gap-2 flex-shrink-0">
                    {r.status === "aberta" && (
                      <>
                        <button onClick={() => navigate("/instituicao/professores")} className="text-xs bg-blue-600 text-white px-3 py-1.5 rounded-lg hover:bg-blue-700 transition-colors font-semibold">
                          Buscar professores
                        </button>
                        <button onClick={() => setConfirmCancel(r.id)} className="text-xs text-red-500 hover:text-red-700 font-medium px-2 py-1.5">
                          Cancelar
                        </button>
                      </>
                    )}
                    {r.status === "aguardando" && (
                      <button onClick={() => setConfirmCancel(r.id)} className="text-xs text-red-500 hover:text-red-700 font-medium">
                        Cancelar
                      </button>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Cancel confirmation modal */}
      {confirmCancel && (
        <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl shadow-xl w-full max-w-sm p-6 text-center">
            <div className="text-4xl mb-3">⚠️</div>
            <h3 className="font-bold text-slate-800 text-lg mb-2">Cancelar solicitação?</h3>
            <p className="text-sm text-slate-500 mb-6">Esta ação não pode ser desfeita. O professor convidado será notificado.</p>
            <div className="flex gap-3">
              <button onClick={() => setConfirmCancel(null)} className="flex-1 border border-slate-200 text-slate-600 hover:bg-slate-50 font-medium py-2.5 rounded-xl text-sm">Manter</button>
              <button onClick={() => handleCancel(confirmCancel)} className="flex-1 bg-red-600 hover:bg-red-700 text-white font-semibold py-2.5 rounded-xl text-sm">Cancelar mesmo assim</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// aulasempre/src/app/features/institution/my-requests/my-requests.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { AppStateService } from '../../../core/services/app-state.service';
import { SubRequest } from '../../../core/models/app.models';

const STATUS_MAP: Record<string, { label: string; cls: string }> = {
  aberta:     { label: 'Buscando professor',     cls: 'badge--aberta' },
  aguardando: { label: 'Aguardando confirmação', cls: 'badge--aguardando' },
  confirmada: { label: 'Professor confirmado',   cls: 'badge--confirmada' },
  recusada:   { label: 'Recusada',               cls: 'badge--recusada' },
  concluida:  { label: 'Concluída',              cls: 'badge--concluida' },
  cancelada:  { label: 'Cancelada',              cls: 'badge--cancelada' },
};

@Component({
  selector: 'app-my-requests',
  standalone: true,
  imports: [CommonModule],
  template: `
<div class="page-content page-enter">
  <div class="page-top">
    <div>
      <h1 class="page-title">Minhas solicitações</h1>
      <p class="page-sub">Gerencie suas solicitações de substituição</p>
    </div>
    <button class="btn btn--primary" (click)="go('/instituicao/solicitar')">+ Nova solicitação</button>
  </div>

  <!-- Filter tabs -->
  <div class="filter-tabs">
    <button *ngFor="let f of filters" class="filter-tab"
      [class.active]="activeFilter() === f.value"
      (click)="activeFilter.set(f.value)">
      {{f.label}}
      @if (countFor(f.value) > 0) {
        <span class="tab-count">{{countFor(f.value)}}</span>
      }
    </button>
  </div>

  <!-- List -->
  @if (filtered().length === 0) {
    <div class="card">
      <div class="empty-state">
        <div class="empty-state__icon">📭</div>
        <p class="empty-state__title">Nenhuma solicitação encontrada</p>
        <p class="empty-state__desc">
          @if (activeFilter() === 'todas') { Crie sua primeira solicitação. }
          @else { Não há solicitações com este status. }
        </p>
        @if (activeFilter() === 'todas') {
          <button class="btn btn--primary" style="margin-top:16px" (click)="go('/instituicao/solicitar')">Criar solicitação</button>
        }
      </div>
    </div>
  } @else {
    <div class="req-list">
      <div class="req-card" *ngFor="let r of filtered()">
        <div class="req-card__top">
          <div>
            <h3 class="req-card__title">{{r.disciplina}} · {{r.turma || r.nivel}}</h3>
            <p class="req-card__sub">{{fmt(r.data)}} · {{r.horarioInicio}} – {{r.horarioFim}} · {{r.modalidade === 'presencial' ? r.cidade : 'Online'}}</p>
          </div>
          <span class="badge" [class]="cls(r.status)">{{label(r.status)}}</span>
        </div>

        @if (r.professorConvidadoNome) {
          <div class="req-card__teacher">
            <span class="teacher-avatar">{{r.professorConvidadoNome.charAt(0)}}</span>
            <span>{{r.professorConvidadoNome}}</span>
            @if (r.status === 'aguardando') { <span class="waiting-chip">Aguardando resposta</span> }
            @if (r.status === 'confirmada') { <span class="confirmed-chip">✓ Confirmado</span> }
          </div>
        }

        <div class="req-card__footer">
          <span class="req-card__val">R$ {{r.valor || 'A combinar'}}</span>
          <div class="req-card__actions">
            @if (r.status === 'aberta') {
              <button class="btn btn--primary btn--sm" (click)="go('/instituicao/professores')">Buscar professor</button>
            }
            @if (['aberta','aguardando'].includes(r.status)) {
              <button class="btn btn--danger btn--sm" (click)="cancel(r.id)">Cancelar</button>
            }
          </div>
        </div>
      </div>
    </div>
  }
</div>
  `,
  styles: [`
    .page-top { display:flex; align-items:flex-start; justify-content:space-between; margin-bottom:24px; gap:16px; flex-wrap:wrap; }
    .page-title { font-size:22px; font-weight:700; color:#0F172A; }
    .page-sub { font-size:13px; color:#94A3B8; margin-top:2px; }
    .filter-tabs { display:flex; gap:4px; flex-wrap:wrap; margin-bottom:20px; background:#F1F5F9; padding:4px; border-radius:12px; }
    .filter-tab {
      display:flex; align-items:center; gap:6px;
      padding:7px 14px; border-radius:9px; font-size:13px; font-weight:500; color:#64748B;
      transition:all .15s;
      &:hover { background:#fff; }
      &.active { background:#fff; color:#0F172A; box-shadow:0 1px 4px rgba(0,0,0,.08); font-weight:600; }
    }
    .tab-count {
      background:#2563EB; color:#fff; font-size:11px; font-weight:700;
      width:18px; height:18px; border-radius:50%; display:flex; align-items:center; justify-content:center;
    }
    .req-list { display:flex; flex-direction:column; gap:14px; }
    .req-card { background:#fff; border:1px solid #E2E8F0; border-radius:16px; padding:20px; box-shadow:0 1px 3px rgba(0,0,0,.05); }
    .req-card__top { display:flex; align-items:flex-start; justify-content:space-between; margin-bottom:12px; gap:12px; }
    .req-card__title { font-size:15px; font-weight:700; color:#0F172A; }
    .req-card__sub { font-size:13px; color:#94A3B8; margin-top:2px; }
    .req-card__teacher {
      display:flex; align-items:center; gap:8px; padding:10px 12px;
      background:#F8FAFC; border-radius:10px; font-size:13px; color:#334155; margin-bottom:12px;
    }
    .teacher-avatar {
      width:28px; height:28px; border-radius:50%; background:#DBEAFE;
      color:#1D4ED8; font-size:12px; font-weight:700;
      display:flex; align-items:center; justify-content:center;
    }
    .waiting-chip { margin-left:auto; font-size:11px; font-weight:600; color:#1D4ED8; background:#DBEAFE; padding:3px 8px; border-radius:9999px; }
    .confirmed-chip { margin-left:auto; font-size:11px; font-weight:600; color:#065F46; background:#D1FAE5; padding:3px 8px; border-radius:9999px; }
    .req-card__footer { display:flex; align-items:center; justify-content:space-between; }
    .req-card__val { font-size:13px; font-weight:600; color:#334155; }
    .req-card__actions { display:flex; gap:8px; }
  `],
})
export class MyRequestsComponent {
  activeFilter = signal<string>('todas');

  filters = [
    { label: 'Todas', value: 'todas' },
    { label: 'Ativas', value: 'ativas' },
    { label: 'Aguardando', value: 'aguardando' },
    { label: 'Confirmadas', value: 'confirmada' },
    { label: 'Concluídas', value: 'concluida' },
    { label: 'Canceladas', value: 'cancelada' },
  ];

  constructor(private router: Router, private appState: AppStateService) {}

  get reqs() { return this.appState.requests; }

  filtered() {
    const f = this.activeFilter();
    if (f === 'todas') return this.reqs;
    if (f === 'ativas') return this.reqs.filter(r => !['concluida','cancelada'].includes(r.status));
    return this.reqs.filter(r => r.status === f);
  }

  countFor(f: string) {
    if (f === 'todas') return this.reqs.length;
    if (f === 'ativas') return this.reqs.filter(r => !['concluida','cancelada'].includes(r.status)).length;
    return this.reqs.filter(r => r.status === f).length;
  }

  fmt(data: string) {
    if (!data) return '—';
    const [y, m, d] = data.split('-');
    return `${d}/${m}/${y}`;
  }
  label(s: string) { return STATUS_MAP[s]?.label || s; }
  cls(s: string) { return STATUS_MAP[s]?.cls || ''; }
  cancel(id: string) { this.appState.cancelRequest(id); }
  go(path: string) { this.router.navigateByUrl(path); }
}
