// Front-end/src/app/features/institution/search-teachers/search-teachers.component.ts
import { Component, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { AppStateService } from '../../../core/services/app-state.service';
import { Teacher } from '../../../core/models/app.models';
import { errorMessage } from '../../../core/services/api.service';

const COLOR_MAP: Record<string, string> = {
  blue: 'avatar--blue',
  green: 'avatar--green',
  purple: 'avatar--purple',
  amber: 'avatar--amber',
};

@Component({
  selector: 'app-search-teachers',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
<div class="page-content page-enter">
  <div class="page-top">
    <div>
      <h1 class="page-title">Buscar professores</h1>
      <p class="page-sub">Encontre professores disponíveis e envie convites</p>
    </div>
  </div>

  <!-- Success banner -->
  @if (success()) {
    <div class="success-banner">
      <span>✅</span>
      <p>{{success()}}</p>
    </div>
  }

  <!-- Select open request -->
  @if (openRequests().length > 0) {
    <div class="select-req-box">
      <p class="select-req-label">Qual solicitação deseja preencher?</p>
      <select [(ngModel)]="selectedRequestId" (ngModelChange)="loadMatches()" class="form-input">
        <option value="">Selecione uma solicitação aberta...</option>
        <option *ngFor="let r of openRequests()" [value]="r.id">
          {{r.disciplina}} · {{r.turma || r.nivel}} · {{fmtDate(r.data)}} · {{r.horarioInicio}}–{{r.horarioFim}}
        </option>
      </select>
    </div>
  } @else {
    <div class="no-req-warning">
      <span>⚠️</span>
      <div>
        <p style="font-size:14px;font-weight:600;color:#92400E">Nenhuma solicitação aberta</p>
        <p style="font-size:13px;color:#B45309;margin-top:2px">Crie uma solicitação antes de convidar professores.</p>
        <button class="link-btn" (click)="go('/instituicao/solicitar')" style="margin-top:4px">Criar solicitação →</button>
      </div>
    </div>
  }

    @if (error()) { <p class="form-error" role="alert">{{error()}}</p> }
    @if (matching()) { <p role="status">Buscando professores compatíveis…</p> }
  <div class="search-layout">
    <!-- Filters -->
    <div class="filters-panel">
      <h3 class="filters-title">Filtros</h3>
      <div class="filter-group">
        <label class="filter-label">Busca</label>
        <input [(ngModel)]="search" class="form-input" placeholder="Nome ou disciplina..." />
      </div>
      <div class="filter-group">
        <label class="filter-label">Disciplina</label>
        <select [(ngModel)]="filterDisciplina" class="form-input">
          <option value="">Todas</option>
          <option *ngFor="let d of allDisciplinas()">{{d}}</option>
        </select>
      </div>
      <label class="filter-check">
        <input type="checkbox" [(ngModel)]="filterAvail" />
        <span>Apenas disponíveis</span>
      </label>

      <!-- Sort -->
      <div class="filter-group" style="margin-top:16px">
        <label class="filter-label">Ordenar por</label>
        <div class="sort-group">
          <button *ngFor="let s of sortOptions" class="sort-btn" [class.active]="sortBy===s.v" (click)="sortBy=s.v">{{s.l}}</button>
        </div>
      </div>
    </div>

    <!-- Results -->
    <div class="results">
      <p class="results-count">{{filtered().length}} professor(es)</p>

      @if (filtered().length === 0) {
        <div class="card">
          <div class="empty-state">
            <div class="empty-state__icon">🔍</div>
            <p class="empty-state__title">Nenhum professor encontrado</p>
            <p class="empty-state__desc">Tente ajustar os filtros de busca.</p>
          </div>
        </div>
      } @else {
        <div class="teacher-list">
          <div class="teacher-card" *ngFor="let t of filtered()">
            <div class="teacher-card__inner">
              <div class="teacher-avatar" [class]="avatarCls(t.cor)">{{t.initials}}</div>
              <div class="teacher-info">
                <div class="teacher-info__top">
                  <div>
                    <div class="teacher-name-row">
                      <h3 class="teacher-name">{{t.nome}}</h3>
                      @if (t.verificado) { <span class="verified-badge">✓ Verificado</span> }
                    </div>
                    <p class="teacher-formacao">{{t.formacao}}</p>
                  </div>
                  <div class="teacher-avail" [class.available]="t.disponivel">
                    <span class="avail-dot" [class.green]="t.disponivel"></span>
                    {{t.disponivel ? 'Disponível' : 'Indisponível'}}
                  </div>
                </div>

                <div class="teacher-stats">
                  <span class="stars-row">{{starsStr(t.nota)}} <b>{{t.nota}}</b></span>
                  <span>📚 {{t.experiencia}} anos</span>
                  <span>📍 {{t.distancia}}</span>
                  <span>🔄 {{t.subs}} subs</span>
                </div>

                <div class="teacher-tags">
                  <span class="tag" *ngFor="let d of t.disciplinas">{{d}}</span>
                </div>

                <div class="teacher-actions">
                  <button class="btn btn--secondary btn--sm" (click)="go('/instituicao/professor/'+t.id)">Ver perfil</button>
                  @if (t.disponivel && !isInvited(t.id)) {
                    <button class="btn btn--primary btn--sm"
                      [disabled]="!selectedRequestId || busy() || matching()"
                      (click)="invite(t.id, t.nome)">
                      {{selectedRequestId ? 'Convidar para substituição' : 'Selecione uma solicitação'}}
                    </button>
                  }
                  @if (isInvited(t.id)) {
                    <span class="invited-chip">✓ Convite enviado</span>
                  }
                </div>
              </div>
            </div>
          </div>
        </div>
      }
    </div>
  </div>
</div>
  `,
  styles: [`
    .page-top { display:flex; align-items:flex-start; justify-content:space-between; margin-bottom:20px; gap:16px; }
    .page-title { font-size:22px; font-weight:700; color:#0F172A; }
    .page-sub { font-size:13px; color:#94A3B8; margin-top:2px; }
    .success-banner { display:flex; align-items:center; gap:10px; background:#F0FDF4; border:1px solid #BBF7D0; border-radius:12px; padding:14px 16px; margin-bottom:16px; font-size:14px; font-weight:600; color:#065F46; }
    .select-req-box { background:#EFF6FF; border:1px solid #BFDBFE; border-radius:14px; padding:16px; margin-bottom:20px;
      p { font-size:14px; font-weight:600; color:#1E40AF; margin-bottom:8px; }
    }
    .select-req-label { font-size:14px; font-weight:600; color:#1E40AF; margin-bottom:8px; }
    .no-req-warning { display:flex; align-items:flex-start; gap:12px; background:#FFFBEB; border:1px solid #FDE68A; border-radius:14px; padding:14px 16px; margin-bottom:20px; font-size:24px; }
    .link-btn { font-size:13px; font-weight:600; color:#2563EB; &:hover{text-decoration:underline;} }
    .search-layout { display:flex; gap:24px; align-items:flex-start; }
    @media(max-width:900px) { .search-layout { flex-direction:column; } .search-layout .filters-panel { width:100%; } }
    .filters-panel { width:220px; flex-shrink:0; background:#fff; border:1px solid #E2E8F0; border-radius:16px; padding:20px; box-shadow:0 1px 3px rgba(0,0,0,.05); }
    .filters-title { font-size:14px; font-weight:700; color:#0F172A; margin-bottom:16px; }
    .filter-group { margin-bottom:14px; }
    .filter-label { display:block; font-size:11px; font-weight:600; color:#94A3B8; text-transform:uppercase; letter-spacing:.05em; margin-bottom:6px; }
    .filter-check { display:flex; align-items:center; gap:8px; font-size:13px; color:#334155; cursor:pointer;
      input { accent-color:#2563EB; }
    }
    .sort-group { display:flex; flex-direction:column; gap:4px; }
    .sort-btn { padding:6px 10px; border-radius:8px; font-size:12px; font-weight:500; color:#64748B; text-align:left; transition:all .15s;
      &:hover { background:#F8FAFC; }
      &.active { background:#EFF6FF; color:#1D4ED8; font-weight:600; }
    }
    .results { flex:1; min-width:0; }
    .results-count { font-size:13px; color:#94A3B8; margin-bottom:12px; }
    .teacher-list { display:flex; flex-direction:column; gap:14px; }
    .teacher-card { background:#fff; border:1px solid #E2E8F0; border-radius:16px; padding:20px; box-shadow:0 1px 3px rgba(0,0,0,.05); transition:box-shadow .2s;
      &:hover { box-shadow:0 4px 14px rgba(0,0,0,.09); }
    }
    .teacher-card__inner { display:flex; gap:16px; }
    .teacher-avatar { width:52px; height:52px; border-radius:14px; font-size:16px; font-weight:700; display:flex; align-items:center; justify-content:center; flex-shrink:0;
      &--blue { background:#DBEAFE; color:#1D4ED8; }
      &--green { background:#D1FAE5; color:#065F46; }
      &--purple { background:#EDE9FE; color:#5B21B6; }
      &--amber { background:#FEF3C7; color:#92400E; }
    }
    .teacher-info { flex:1; min-width:0; }
    .teacher-info__top { display:flex; align-items:flex-start; justify-content:space-between; margin-bottom:8px; gap:10px; }
    .teacher-name-row { display:flex; align-items:center; gap:8px; flex-wrap:wrap; }
    .teacher-name { font-size:16px; font-weight:700; color:#0F172A; }
    .teacher-formacao { font-size:12px; color:#94A3B8; margin-top:2px; }
    .verified-badge { background:#DBEAFE; color:#1D4ED8; font-size:11px; font-weight:600; padding:2px 8px; border-radius:9999px; }
    .teacher-avail { font-size:12px; font-weight:500; color:#94A3B8; display:flex; align-items:center; gap:4px; flex-shrink:0;
      &.available { color:#16A34A; }
    }
    .avail-dot { width:6px; height:6px; border-radius:50%; background:#CBD5E1;
      &.green { background:#4ADE80; }
    }
    .teacher-stats { display:flex; align-items:center; gap:14px; flex-wrap:wrap; font-size:12px; color:#64748B; margin-bottom:8px; }
    .stars-row { display:flex; align-items:center; gap:4px; b { color:#0F172A; } }
    .teacher-tags { display:flex; flex-wrap:wrap; gap:6px; margin-bottom:10px; }
    .tag { background:#F1F5F9; color:#475569; font-size:12px; padding:3px 8px; border-radius:6px; }
    .teacher-actions { display:flex; gap:8px; flex-wrap:wrap; }
    .invited-chip { font-size:12px; font-weight:600; color:#1D4ED8; background:#EFF6FF; padding:6px 12px; border-radius:10px; }
  `],
})
export class SearchTeachersComponent {
  search = '';
  filterDisciplina = '';
  filterAvail = false;
  sortBy = 'nota';
  selectedRequestId = '';
  invitedId: string | null = null;
  success = signal<string | null>(null);
  error = signal('');
  busy = signal(false);
  matching = signal(false);
  matchIds = signal<string[] | null>(null);

  sortOptions = [
    { v: 'nota', l: 'Melhor avaliação' },
    { v: 'subs', l: 'Mais substituições' },
    { v: 'experiencia', l: 'Mais experiência' },
  ];

  constructor(private router: Router, private appState: AppStateService) { void appState.retry(); }

  openRequests() { return this.appState.requests.filter(r => ['aberta','aguardando'].includes(r.status)); }

  async loadMatches() {
    const id = this.selectedRequestId; this.matchIds.set(null); this.error.set(''); this.invitedId = null;
    if (!id) { this.matching.set(false); return; }
    this.matching.set(true);
    try { const ids = await this.appState.compatibleTeachers(id); if (id === this.selectedRequestId) this.matchIds.set(ids); }
    catch (e) { if (id === this.selectedRequestId) this.error.set(errorMessage(e)); }
    finally { if (id === this.selectedRequestId) this.matching.set(false); }
  }

  allDisciplinas() {
    return Array.from(new Set(this.appState.teachers.flatMap(t => t.disciplinas))).sort();
  }

  filtered(): Teacher[] {
    const selectedReq = this.openRequests().find(r => r.id === this.selectedRequestId);
    return this.appState.teachers
      .filter(t => {
        if (selectedReq && !this.matchIds()?.includes(t.id)) return false;
        if (this.filterAvail && !t.disponivel) return false;
        if (this.filterDisciplina && !t.disciplinas.includes(this.filterDisciplina)) return false;
        if (this.search) {
          const s = this.search.toLowerCase();
          if (!t.nome.toLowerCase().includes(s) && !t.disciplinas.join(' ').toLowerCase().includes(s)) return false;
        }
        if (selectedReq && selectedReq.recusadoPorIds.includes(t.id)) return false;
        return true;
      })
      .sort((a, b) => {
        if (this.sortBy === 'nota') return b.nota - a.nota;
        if (this.sortBy === 'subs') return b.subs - a.subs;
        return b.experiencia - a.experiencia;
      });
  }

  isInvited(id: string) {
    if (this.invitedId === id) return true;
    const selectedReq = this.openRequests().find(r => r.id === this.selectedRequestId);
    return selectedReq?.invitedTeacherIds?.includes(id) || selectedReq?.professorConvidadoId === id;
  }

  async invite(teacherId: string, teacherNome: string) {
    if (!this.selectedRequestId || this.busy()) return;
    this.busy.set(true); this.error.set('');
    try {
    await this.appState.inviteTeacher(this.selectedRequestId, teacherId, teacherNome);
    this.invitedId = teacherId;
    this.success.set(`Convite enviado para ${teacherNome}! Aguardando resposta.`);
    setTimeout(() => this.router.navigateByUrl('/instituicao/solicitacoes'), 2000);
    } catch (e) { this.error.set(errorMessage(e)); }
    finally { this.busy.set(false); }
  }

  starsStr(nota: number) {
    const full = Math.round(nota);
    return '★'.repeat(full) + '☆'.repeat(5 - full);
  }
  fmtDate(data: string) {
    if (!data) return '';
    const [y, m, d] = data.split('-');
    return `${d}/${m}/${y}`;
  }
  avatarCls(cor: string) { return `teacher-avatar ${COLOR_MAP[cor] || 'avatar--blue'}`; }
  go(path: string) { this.router.navigateByUrl(path); }
}

// Projeto antigo/Front-end/src/screens/institution/SearchTeachers.tsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useApp, SubRequest } from "../../store/AppContext";

function Stars({ nota }: { nota: number }) {
  return (
    <span className="flex items-center gap-0.5">
      {[1,2,3,4,5].map((i) => (
        <svg key={i} width="12" height="12" viewBox="0 0 20 20" fill={i <= Math.round(nota) ? "#F59E0B" : "#E2E8F0"}>
          <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
        </svg>
      ))}
    </span>
  );
}

const colorMap: Record<string, string> = {
  blue: "bg-blue-100 text-blue-700",
  green: "bg-green-100 text-green-700",
  purple: "bg-purple-100 text-purple-700",
  amber: "bg-amber-100 text-amber-700",
};

export default function SearchTeachers() {
  const navigate = useNavigate();
  const { teachers, requests, inviteTeacher } = useApp();
  const [search, setSearch] = useState("");
  const [filterDisciplina, setFilterDisciplina] = useState("");
  const [filterAvail, setFilterAvail] = useState(false);
  const [sortBy, setSortBy] = useState("nota");
  const [selectedRequestId, setSelectedRequestId] = useState<string>("");
  const [invitedId, setInvitedId] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);

  const openRequests = requests.filter((r) => r.status === "aberta");
  const selectedRequest = openRequests.find((r) => r.id === selectedRequestId);

  const filtered = teachers
    .filter((t) => {
      if (filterAvail && !t.disponivel) return false;
      if (filterDisciplina && !t.disciplinas.includes(filterDisciplina)) return false;
      if (search && !t.nome.toLowerCase().includes(search.toLowerCase()) && !t.disciplinas.join(" ").toLowerCase().includes(search.toLowerCase())) return false;
      // Hide teachers already declined for selected request
      if (selectedRequest && selectedRequest.recusadoPorIds.includes(t.id)) return false;
      return true;
    })
    .sort((a, b) => {
      if (sortBy === "nota") return b.nota - a.nota;
      if (sortBy === "subs") return b.subs - a.subs;
      return parseFloat(a.distancia) - parseFloat(b.distancia);
    });

  const allDisciplinas = Array.from(new Set(teachers.flatMap((t) => t.disciplinas))).sort();

  const handleInvite = (teacherId: string, teacherNome: string) => {
    if (!selectedRequestId) {
      alert("Selecione primeiro qual solicitação você quer preencher.");
      return;
    }
    inviteTeacher(selectedRequestId, teacherId, teacherNome);
    setInvitedId(teacherId);
    setSuccess(`Convite enviado para ${teacherNome}! Aguardando resposta.`);
    setTimeout(() => navigate("/instituicao/solicitacoes"), 2000);
  };

  return (
    <div className="p-8">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-slate-800">Buscar professores</h1>
        <p className="text-sm text-slate-500 mt-1">Encontre professores disponíveis e envie convites</p>
      </div>

      {success && (
        <div className="mb-5 bg-green-50 border border-green-200 rounded-xl p-4 flex items-center gap-3">
          <span className="text-green-600 text-xl">✅</span>
          <p className="text-sm font-semibold text-green-800">{success}</p>
        </div>
      )}

      {/* Select request */}
      {openRequests.length > 0 && (
        <div className="bg-blue-50 border border-blue-100 rounded-xl p-4 mb-6">
          <p className="text-sm font-semibold text-slate-700 mb-2">Qual solicitação deseja preencher?</p>
          <select
            value={selectedRequestId}
            onChange={(e) => setSelectedRequestId(e.target.value)}
            className="w-full px-4 py-2.5 rounded-xl border border-blue-200 text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
          >
            <option value="">Selecione uma solicitação aberta...</option>
            {openRequests.map((r) => (
              <option key={r.id} value={r.id}>
                {r.disciplina} · {r.turma || r.nivel} · {r.data ? new Date(r.data + "T00:00:00").toLocaleDateString("pt-BR") : ""} · {r.horarioInicio}–{r.horarioFim}
              </option>
            ))}
          </select>
        </div>
      )}

      {openRequests.length === 0 && (
        <div className="bg-amber-50 border border-amber-100 rounded-xl p-4 mb-6 flex items-start gap-3">
          <span className="text-amber-500 text-lg">⚠️</span>
          <div>
            <p className="text-sm font-semibold text-amber-800">Nenhuma solicitação aberta</p>
            <p className="text-xs text-amber-700 mt-0.5">Crie uma solicitação antes de convidar professores.</p>
            <button onClick={() => navigate("/instituicao/solicitar")} className="text-xs text-blue-600 font-semibold hover:underline mt-1">
              Criar solicitação →
            </button>
          </div>
        </div>
      )}

      <div className="flex gap-6">
        {/* Filters */}
        <div className="w-52 flex-shrink-0">
          <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-4 space-y-4">
            <h3 className="text-sm font-semibold text-slate-700">Filtros</h3>
            <div>
              <label className="text-xs font-medium text-slate-500 uppercase tracking-wide mb-2 block">Busca</label>
              <input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Nome ou disciplina..." className="w-full px-3 py-2 rounded-lg border border-slate-200 text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-blue-500" />
            </div>
            <div>
              <label className="text-xs font-medium text-slate-500 uppercase tracking-wide mb-2 block">Disciplina</label>
              <select value={filterDisciplina} onChange={(e) => setFilterDisciplina(e.target.value)} className="w-full px-3 py-2 rounded-lg border border-slate-200 text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white">
                <option value="">Todas</option>
                {allDisciplinas.map((d) => <option key={d}>{d}</option>)}
              </select>
            </div>
            <label className="flex items-center gap-2 cursor-pointer">
              <input type="checkbox" checked={filterAvail} onChange={(e) => setFilterAvail(e.target.checked)} className="accent-blue-600" />
              <span className="text-sm text-slate-700">Apenas disponíveis</span>
            </label>
          </div>
        </div>

        {/* Results */}
        <div className="flex-1">
          <div className="flex items-center justify-between mb-4">
            <p className="text-sm text-slate-500">{filtered.length} professor(es)</p>
            <div className="flex gap-1 bg-slate-100 p-1 rounded-xl">
              {[{ v: "nota", l: "Melhor avaliação" }, { v: "subs", l: "Mais substituições" }, { v: "dist", l: "Mais próximo" }].map(({ v, l }) => (
                <button key={v} onClick={() => setSortBy(v)} className={`text-xs px-3 py-1.5 rounded-lg font-medium transition-all ${sortBy === v ? "bg-white text-slate-800 shadow-sm" : "text-slate-500 hover:text-slate-700"}`}>{l}</button>
              ))}
            </div>
          </div>

          {filtered.length === 0 ? (
            <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-12 text-center">
              <div className="text-4xl mb-3">🔍</div>
              <p className="font-semibold text-slate-700">Nenhum professor encontrado</p>
              <p className="text-sm text-slate-400 mt-1">Tente ajustar os filtros de busca.</p>
            </div>
          ) : (
            <div className="space-y-4">
              {filtered.map((t) => {
                const alreadyInvited = invitedId === t.id ||
                  (selectedRequest?.professorConvidadoId === t.id && selectedRequest?.status === "aguardando");
                return (
                  <div key={t.id} className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5 hover:shadow-md transition-all">
                    <div className="flex gap-4">
                      <div className={`w-14 h-14 rounded-2xl flex items-center justify-center text-lg font-bold flex-shrink-0 ${colorMap[t.cor]}`}>
                        {t.initials}
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-start justify-between gap-3">
                          <div>
                            <div className="flex items-center gap-2 flex-wrap">
                              <h3 className="font-bold text-slate-800">{t.nome}</h3>
                              {t.verificado && <span className="bg-blue-100 text-blue-700 text-xs font-semibold px-2 py-0.5 rounded-full">✓ Verificado</span>}
                            </div>
                            <p className="text-xs text-slate-500 mt-0.5">{t.formacao}</p>
                          </div>
                          <div className="text-right flex-shrink-0">
                            <div className={`w-2 h-2 rounded-full inline-block mr-1 ${t.disponivel ? "bg-green-400" : "bg-slate-300"}`} />
                            <span className={`text-xs font-medium ${t.disponivel ? "text-green-600" : "text-slate-400"}`}>
                              {t.disponivel ? "Disponível" : "Indisponível"}
                            </span>
                          </div>
                        </div>
                        <div className="flex items-center gap-4 mt-2 flex-wrap">
                          <div className="flex items-center gap-1"><Stars nota={t.nota} /><span className="text-xs font-semibold text-slate-700 ml-1">{t.nota}</span></div>
                          <span className="text-xs text-slate-500">📚 {t.experiencia} anos</span>
                          <span className="text-xs text-slate-500">📍 {t.distancia}</span>
                          <span className="text-xs text-slate-500">🔄 {t.subs} substituições</span>
                        </div>
                        <div className="flex items-center gap-2 mt-3 flex-wrap">
                          {t.disciplinas.map((d) => (
                            <span key={d} className="bg-slate-100 text-slate-600 text-xs px-2 py-0.5 rounded-lg">{d}</span>
                          ))}
                        </div>
                        <div className="flex gap-2 mt-4">
                          <button onClick={() => navigate(`/instituicao/professor/${t.id}`)} className="border border-slate-200 text-slate-700 hover:bg-slate-50 text-xs font-medium px-3 py-2 rounded-xl transition-all">
                            Ver perfil
                          </button>
                          {t.disponivel && !alreadyInvited && (
                            <button
                              onClick={() => handleInvite(t.id, t.nome)}
                              disabled={!selectedRequestId}
                              className="bg-blue-600 hover:bg-blue-700 disabled:bg-slate-300 disabled:cursor-not-allowed text-white text-xs font-semibold px-4 py-2 rounded-xl transition-all"
                            >
                              {!selectedRequestId ? "Selecione uma solicitação" : "Convidar para substituição"}
                            </button>
                          )}
                          {alreadyInvited && (
                            <span className="text-xs text-blue-600 font-semibold px-3 py-2 bg-blue-50 rounded-xl">
                              ✓ Convite enviado
                            </span>
                          )}
                        </div>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
