// Front-end/src/app/features/teacher/confirmed/teacher-confirmed.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AppStateService } from '../../../core/services/app-state.service';
import { SubRequest } from '../../../core/models/app.models';

@Component({
  selector: 'app-teacher-confirmed',
  standalone: true,
  imports: [CommonModule],
  template: `
<div class="page-content page-enter">
  <div class="page-header">
    <h1 class="page-title">Substituições confirmadas</h1>
    <p class="page-sub">Todas as substituições que você confirmou</p>
  </div>

  @if (confirmed.length === 0) {
    <div class="card empty-card">
      <div class="empty-state">
        <div class="empty-state__icon">📅</div>
        <h3 class="empty-state__title">Nenhuma substituição confirmada</h3>
        <p class="empty-state__desc">Aceite convites para ver as substituições confirmadas aqui.</p>
      </div>
    </div>
  } @else {
    <div class="confirmed-list">
      <div class="card confirmed-card" *ngFor="let r of confirmed">
        <div class="confirmed-card__header">
          <div>
            <h3 class="confirmed-card__title">{{r.disciplina}}</h3>
            <p class="confirmed-card__sub">{{r.turma || r.nivel}} · {{r.instituicaoNome}}</p>
          </div>
          <span class="badge badge--confirmada">{{r.status === 'concluida' ? 'Concluída' : '✓ Confirmada'}}</span>
        </div>

        <div class="details-grid">
          <div class="detail-box">
            <p class="detail-box__key">📅 Data</p>
            <p class="detail-box__val">{{fmt(r.data)}}</p>
          </div>
          <div class="detail-box">
            <p class="detail-box__key">🕐 Horário</p>
            <p class="detail-box__val">{{r.horarioInicio}} – {{r.horarioFim}}</p>
          </div>
          <div class="detail-box">
            <p class="detail-box__key">📍 Local</p>
            <p class="detail-box__val">
              {{r.modalidade === 'presencial' ? r.cidade + (r.endereco ? ' (' + r.endereco + ')' : '') : 'Online'}}
            </p>
          </div>
          <div class="detail-box">
            <p class="detail-box__key">💰 Valor</p>
            <p class="detail-box__val">R$ {{r.valor}}</p>
          </div>
        </div>

        @if (r.observacoes) {
          <div class="notes-box">
            <p class="notes-box__title">📝 Observações</p>
            <p class="notes-box__content">{{r.observacoes}}</p>
          </div>
        }
      </div>
    </div>
  }
</div>
  `,
  styles: [`
    .page-header { margin-bottom: 24px; }
    .page-title { font-size: 22px; font-weight: 700; color: #0F172A; }
    .page-sub { font-size: 13px; color: #94A3B8; margin-top: 2px; }

    .confirmed-list { display: flex; flex-direction: column; gap: 16px; }

    .confirmed-card {
      padding: 24px; border: 1.5px solid #BBF7D0;
    }
    .confirmed-card__header {
      display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 16px;
    }
    .confirmed-card__title { font-size: 18px; font-weight: 700; color: #0F172A; }
    .confirmed-card__sub { font-size: 14px; color: #64748B; margin-top: 2px; }

    .details-grid {
      display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      gap: 10px;
    }
    .detail-box {
      background: #F8FAFC; border-radius: 12px; padding: 12px 14px;
    }
    .detail-box__key { font-size: 11px; color: #94A3B8; margin-bottom: 3px; font-weight: 500; }
    .detail-box__val { font-size: 13px; font-weight: 600; color: #0F172A; }

    .notes-box {
      margin-top: 14px; background: #F0FDF4; border: 1px solid #DCFCE7;
      border-radius: 12px; padding: 12px 16px;
    }
    .notes-box__title { font-size: 11px; font-weight: 600; color: #166534; margin-bottom: 3px; }
    .notes-box__content { font-size: 13px; color: #15803D; line-height: 1.5; }
  `],
})
export class TeacherConfirmedComponent {
  constructor(private appState: AppStateService) { void appState.retry(); }

  get currentTeacher() { return this.appState.currentTeacher; }

  get confirmed(): SubRequest[] {
    return this.appState.requests.filter(
      r => ['confirmada','concluida'].includes(r.status) && r.professorConfirmadoId === this.currentTeacher.id
    );
  }

  fmt(data: string) {
    if (!data) return '—';
    const [y, m, d] = data.split('-');
    return `${d}/${m}/${y}`;
  }
}

// Projeto antigo/src/screens/teacher/TeacherConfirmed.tsx
import { useApp } from "../../store/AppContext";

function fmt(data: string) {
  if (!data) return "—";
  const [y, m, d] = data.split("-");
  return `${d}/${m}/${y}`;
}

export default function TeacherConfirmed() {
  const { requests, currentTeacher } = useApp();
  const confirmed = requests.filter((r) => r.status === "confirmada" && r.professorConfirmadoId === currentTeacher.id);

  return (
    <div className="p-8 max-w-3xl mx-auto">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-slate-800">Substituições confirmadas</h1>
        <p className="text-sm text-slate-500 mt-1">Todas as substituições que você confirmou</p>
      </div>

      {confirmed.length === 0 ? (
        <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-16 text-center">
          <div className="text-5xl mb-4">📅</div>
          <h3 className="font-semibold text-slate-700 mb-1">Nenhuma substituição confirmada</h3>
          <p className="text-sm text-slate-400">Aceite convites para ver as substituições confirmadas aqui.</p>
        </div>
      ) : (
        <div className="space-y-4">
          {confirmed.map((r) => (
            <div key={r.id} className="bg-white rounded-2xl border border-green-100 shadow-sm p-6">
              <div className="flex items-start justify-between mb-4">
                <div>
                  <h3 className="font-bold text-slate-800">{r.disciplina}</h3>
                  <p className="text-sm text-slate-500">{r.turma || r.nivel} · {r.instituicaoNome}</p>
                </div>
                <span className="bg-green-100 text-green-700 text-xs font-semibold px-3 py-1.5 rounded-full">✓ Confirmada</span>
              </div>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                {[
                  ["📅 Data", fmt(r.data)],
                  ["🕐 Horário", `${r.horarioInicio} – ${r.horarioFim}`],
                  ["📍 Local", r.modalidade === "presencial" ? r.cidade : "Online"],
                  ["💰 Valor", `R$ ${r.valor}`],
                ].map(([label, value]) => (
                  <div key={label} className="bg-slate-50 rounded-xl p-3">
                    <p className="text-xs text-slate-400 mb-0.5">{label}</p>
                    <p className="text-sm font-semibold text-slate-800">{value}</p>
                  </div>
                ))}
              </div>
              {r.observacoes && (
                <div className="mt-3 bg-green-50 rounded-xl p-3">
                  <p className="text-xs text-slate-400 mb-0.5">📝 Observações</p>
                  <p className="text-sm text-slate-700">{r.observacoes}</p>
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
