// Front-end/src/app/features/teacher/invites/teacher-invites.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { AppStateService } from '../../../core/services/app-state.service';
import { SubRequest } from '../../../core/models/app.models';

@Component({
  selector: 'app-teacher-invites',
  standalone: true,
  imports: [CommonModule],
  template: `
<div class="page-content page-enter">
  <div class="page-header">
    <h1 class="page-title">Convites recebidos</h1>
    <p class="page-sub">Aceite ou recuse convites de substituição</p>
  </div>

  @if (pending.length === 0 && others.length === 0) {
    <div class="card empty-card">
      <div class="empty-state">
        <div class="empty-state__icon">✉️</div>
        <h3 class="empty-state__title">Nenhum convite recebido</h3>
        <p class="empty-state__desc">Quando uma escola te convidar, o convite aparecerá aqui.</p>
      </div>
    </div>
  } @else {
    <div class="invites-container">
      <!-- Pending invites -->
      @if (pending.length > 0) {
        <div class="invites-section">
          <h2 class="section-title">Aguardando sua resposta ({{pending.length}})</h2>
          <div class="cards-list">
            <div class="card invite-card" *ngFor="let r of pending">
              <div class="invite-card__header">
                <div>
                  <h3 class="invite-card__title">{{r.disciplina}}</h3>
                  <p class="invite-card__sub">{{r.turma || r.nivel}}</p>
                </div>
                <span class="badge badge--aguardando">Novo convite</span>
              </div>

              <div class="details-grid">
                <div class="detail-box">
                  <p class="detail-box__key">🏢 Instituição</p>
                  <p class="detail-box__val">{{r.instituicaoNome}}</p>
                </div>
                <div class="detail-box">
                  <p class="detail-box__key">📅 Data</p>
                  <p class="detail-box__val">{{fmt(r.data)}}</p>
                </div>
                <div class="detail-box">
                  <p class="detail-box__key">🕐 Horário</p>
                  <p class="detail-box__val">{{r.horarioInicio}} – {{r.horarioFim}}</p>
                </div>
                <div class="detail-box">
                  <p class="detail-box__key">📍 Modalidade</p>
                  <p class="detail-box__val">
                    {{r.modalidade === 'presencial' ? 'Presencial – ' + r.cidade : 'Online'}}
                  </p>
                </div>
                <div class="detail-box">
                  <p class="detail-box__key">💰 Valor</p>
                  <p class="detail-box__val">R$ {{r.valor}}</p>
                </div>
                @if (r.turma) {
                  <div class="detail-box">
                    <p class="detail-box__key">👥 Turma</p>
                    <p class="detail-box__val">{{r.turma}}</p>
                  </div>
                }
              </div>

              @if (r.observacoes) {
                <div class="notes-box">
                  <p class="notes-box__title">📝 Observações da instituição</p>
                  <p class="notes-box__content">{{r.observacoes}}</p>
                </div>
              }

              <div class="actions-row">
                <button class="btn btn--danger btn--lg" style="flex: 1;" (click)="decline(r.id)">
                  Recusar convite
                </button>
                <button class="btn btn--success btn--lg" style="flex: 1;" (click)="accept(r.id)">
                  Aceitar convite
                </button>
              </div>
            </div>
          </div>
        </div>
      }

      <!-- History of invites -->
      @if (others.length > 0) {
        <div class="invites-section" style="margin-top: 32px;">
          <h2 class="section-title">Histórico de convites</h2>
          <div class="cards-list">
            <div class="card history-card" *ngFor="let r of others">
              <div class="history-card__inner">
                <div>
                  <p class="history-card__title">{{r.disciplina}} · {{r.turma || r.nivel}}</p>
                  <p class="history-card__sub">{{r.instituicaoNome}} · {{fmt(r.data)}}</p>
                </div>
                <span class="badge" [class.badge--confirmada]="r.status === 'confirmada'" [class.badge--recusada]="r.status !== 'confirmada'">
                  {{r.status === 'confirmada' ? 'Aceito ✓' : 'Recusado'}}
                </span>
              </div>
            </div>
          </div>
        </div>
      }
    </div>
  }
</div>
  `,
  styles: [`
    .page-header { margin-bottom: 24px; }
    .page-title { font-size: 22px; font-weight: 700; color: #0F172A; }
    .page-sub { font-size: 13px; color: #94A3B8; margin-top: 2px; }

    .invites-container { display: flex; flex-direction: column; gap: 24px; }
    .section-title {
      font-size: 12px; font-weight: 700; color: #64748B;
      text-transform: uppercase; letter-spacing: .05em; margin-bottom: 14px;
    }
    .cards-list { display: flex; flex-direction: column; gap: 16px; }

    .invite-card {
      padding: 24px; border: 2px solid #BFDBFE;
    }
    .invite-card__header {
      display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 16px;
    }
    .invite-card__title { font-size: 18px; font-weight: 700; color: #0F172A; }
    .invite-card__sub { font-size: 14px; color: #64748B; margin-top: 2px; }

    .details-grid {
      display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      gap: 10px; margin-bottom: 16px;
    }
    .detail-box {
      background: #F8FAFC; border-radius: 12px; padding: 12px 14px;
    }
    .detail-box__key { font-size: 11px; color: #94A3B8; margin-bottom: 3px; font-weight: 500; }
    .detail-box__val { font-size: 13px; font-weight: 600; color: #0F172A; }

    .notes-box {
      background: #FFFBEB; border: 1px solid #FEF3C7; border-radius: 12px;
      padding: 14px 16px; margin-bottom: 18px;
    }
    .notes-box__title { font-size: 11px; font-weight: 600; color: #B45309; margin-bottom: 4px; }
    .notes-box__content { font-size: 13px; color: #92400E; line-height: 1.5; }

    .actions-row { display: flex; gap: 12px; }

    .history-card { padding: 16px 20px; }
    .history-card__inner {
      display: flex; align-items: center; justify-content: space-between;
    }
    .history-card__title { font-size: 14px; font-weight: 600; color: #0F172A; }
    .history-card__sub { font-size: 12px; color: #64748B; margin-top: 2px; }
  `],
})
export class TeacherInvitesComponent {
  constructor(private appState: AppStateService, private router: Router) {}

  get currentTeacher() { return this.appState.currentTeacher; }

  get myInvites(): SubRequest[] {
    return this.appState.requests.filter(
      r => r.professorConvidadoId === this.currentTeacher.id
    );
  }

  get pending(): SubRequest[] {
    return this.myInvites.filter(r => r.status === 'aguardando');
  }

  get others(): SubRequest[] {
    return this.myInvites.filter(r => r.status !== 'aguardando');
  }

  accept(requestId: string) {
    this.appState.acceptInvite(requestId);
  }

  decline(requestId: string) {
    this.appState.declineInvite(requestId);
  }

  fmt(data: string) {
    if (!data) return '—';
    const [y, m, d] = data.split('-');
    return `${d}/${m}/${y}`;
  }
}

// Projeto antigo/src/screens/teacher/TeacherInvites.tsx
import { useNavigate } from "react-router-dom";
import { useApp } from "../../store/AppContext";

function fmt(data: string) {
  if (!data) return "—";
  const [y, m, d] = data.split("-");
  return `${d}/${m}/${y}`;
}

export default function TeacherInvites() {
  const navigate = useNavigate();
  const { requests, currentTeacher, acceptInvite, declineInvite } = useApp();

  const myInvites = requests.filter(
    (r) => r.professorConvidadoId === currentTeacher.id && (r.status === "aguardando" || r.status === "confirmada" || r.status === "aberta")
  );
  const pending = myInvites.filter((r) => r.status === "aguardando");
  const others = myInvites.filter((r) => r.status !== "aguardando");

  return (
    <div className="p-8 max-w-3xl mx-auto">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-slate-800">Convites recebidos</h1>
        <p className="text-sm text-slate-500 mt-1">Aceite ou recuse convites de substituição</p>
      </div>

      {pending.length === 0 && others.length === 0 ? (
        <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-16 text-center">
          <div className="text-5xl mb-4">✉️</div>
          <h3 className="font-semibold text-slate-700 mb-1">Nenhum convite recebido</h3>
          <p className="text-sm text-slate-400">Quando uma escola te convidar, o convite aparecerá aqui.</p>
        </div>
      ) : (
        <div className="space-y-5">
          {pending.length > 0 && (
            <div>
              <h2 className="text-sm font-semibold text-slate-500 uppercase tracking-wide mb-3">Aguardando sua resposta ({pending.length})</h2>
              <div className="space-y-4">
                {pending.map((r) => (
                  <div key={r.id} className="bg-white rounded-2xl border-2 border-blue-200 shadow-sm p-6">
                    <div className="flex items-start justify-between mb-4">
                      <div>
                        <h3 className="font-bold text-slate-800 text-lg">{r.disciplina}</h3>
                        <p className="text-slate-500 text-sm">{r.turma || r.nivel}</p>
                      </div>
                      <span className="bg-blue-100 text-blue-700 text-xs font-semibold px-3 py-1.5 rounded-full">Novo convite</span>
                    </div>

                    <div className="grid grid-cols-2 gap-3 mb-4">
                      {[
                        ["🏢 Instituição", r.instituicaoNome],
                        ["📅 Data", fmt(r.data)],
                        ["🕐 Horário", `${r.horarioInicio} – ${r.horarioFim}`],
                        ["📍 Modalidade", r.modalidade === "presencial" ? `Presencial – ${r.cidade}` : "Online"],
                        ["💰 Valor", `R$ ${r.valor}`],
                        ...(r.turma ? [["👥 Turma", r.turma] as [string, string]] : []),
                      ].map(([label, value]) => (
                        <div key={label} className="bg-slate-50 rounded-xl p-3">
                          <p className="text-xs text-slate-400 mb-0.5">{label}</p>
                          <p className="text-sm font-semibold text-slate-800">{value}</p>
                        </div>
                      ))}
                    </div>

                    {r.observacoes && (
                      <div className="bg-amber-50 border border-amber-100 rounded-xl p-3 mb-4">
                        <p className="text-xs text-slate-500 mb-0.5">📝 Observações da instituição</p>
                        <p className="text-sm text-slate-700">{r.observacoes}</p>
                      </div>
                    )}

                    <div className="flex gap-3">
                      <button
                        onClick={() => { declineInvite(r.id); }}
                        className="flex-1 border-2 border-red-200 text-red-600 hover:bg-red-50 font-semibold py-3 rounded-xl transition-all text-sm"
                      >
                        Recusar convite
                      </button>
                      <button
                        onClick={() => { acceptInvite(r.id); }}
                        className="flex-1 bg-green-600 hover:bg-green-700 text-white font-bold py-3 rounded-xl transition-all shadow-sm text-sm"
                      >
                        Aceitar convite
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {others.length > 0 && (
            <div>
              <h2 className="text-sm font-semibold text-slate-500 uppercase tracking-wide mb-3">Histórico de convites</h2>
              <div className="space-y-3">
                {others.map((r) => (
                  <div key={r.id} className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5">
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="font-semibold text-slate-800">{r.disciplina} · {r.turma || r.nivel}</p>
                        <p className="text-xs text-slate-500 mt-0.5">{r.instituicaoNome} · {fmt(r.data)}</p>
                      </div>
                      <span className={`text-xs font-semibold px-2.5 py-1 rounded-full ${r.status === "confirmada" ? "bg-green-100 text-green-700" : "bg-slate-100 text-slate-600"}`}>
                        {r.status === "confirmada" ? "Aceito ✓" : "Recusado"}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
