// Projeto antigo/src/screens/LandingPage.tsx
import { useNavigate } from "react-router-dom";

function Logo({ dark = false }: { dark?: boolean }) {
  return (
    <div className="flex items-center gap-2.5">
      <div className="w-9 h-9 bg-blue-600 rounded-xl flex items-center justify-center shadow-sm">
        <svg width="18" height="18" viewBox="0 0 18 18" fill="none">
          <path d="M9 1.5L15.5 5.25V12.75L9 16.5L2.5 12.75V5.25L9 1.5Z" fill="white" />
          <path d="M6 9L8.5 11.5L12.5 7" stroke="#2563EB" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      </div>
      <span className={`font-bold text-xl tracking-tight ${dark ? "text-white" : "text-slate-800"}`}>
        Aula<span className="text-blue-600">Sempre</span>
      </span>
    </div>
  );
}

const steps = [
  {
    num: "1",
    title: "Solicite a substituição",
    desc: "Informe disciplina, data, horário e nível de ensino. O sistema notifica professores disponíveis na sua região.",
    icon: "📋",
  },
  {
    num: "2",
    title: "Encontre o professor ideal",
    desc: "Veja perfis verificados, avaliações de outras escolas, experiência e compatibilidade com a sua necessidade.",
    icon: "🔍",
  },
  {
    num: "3",
    title: "Confirme e acompanhe",
    desc: "Envie o convite, receba a confirmação e acompanhe tudo pelo painel. Professor e escola recebem todos os detalhes.",
    icon: "✅",
  },
];

const institutionBenefits = [
  "Professores disponíveis na sua cidade",
  "Perfis verificados com avaliações reais",
  "Fluxo rápido — solicitação em menos de 3 minutos",
  "Histórico e avaliações de todas as substituições",
  "Sem cancelamento de aulas por falta de professor",
];

const teacherBenefits = [
  "Receba convites para substituições próximas a você",
  "Escolha aceitar ou recusar cada convite",
  "Acumule avaliações e fortaleça seu perfil",
  "Flexibilidade de horário e modalidade",
  "Renda extra sem compromisso fixo",
];

export default function LandingPage() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-white font-['Inter',sans-serif]">
      {/* Nav */}
      <nav className="sticky top-0 z-40 bg-white/95 backdrop-blur border-b border-slate-100">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <Logo />
          <div className="flex items-center gap-3">
            <button
              onClick={() => navigate("/entrar")}
              className="text-sm font-medium text-slate-600 hover:text-slate-800 transition-colors px-3 py-2"
            >
              Entrar
            </button>
            <button
              onClick={() => navigate("/demo")}
              className="bg-blue-600 hover:bg-blue-700 text-white text-sm font-semibold px-4 py-2 rounded-xl transition-all shadow-sm"
            >
              Experimentar demonstração
            </button>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="bg-gradient-to-br from-blue-700 via-blue-600 to-blue-500 relative overflow-hidden">
        <div className="absolute inset-0 opacity-10">
          <svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <pattern id="grid" width="48" height="48" patternUnits="userSpaceOnUse">
                <path d="M 48 0 L 0 0 0 48" fill="none" stroke="white" strokeWidth="1" />
              </pattern>
            </defs>
            <rect width="100%" height="100%" fill="url(#grid)" />
          </svg>
        </div>
        <div className="max-w-6xl mx-auto px-6 py-24 md:py-32 relative z-10">
          <div className="max-w-3xl">
            <div className="inline-flex items-center gap-2 bg-white/15 text-white text-sm font-medium px-4 py-2 rounded-full mb-8 border border-white/20">
              <span className="w-2 h-2 bg-green-400 rounded-full animate-pulse" />
              Plataforma de substituição para escolas privadas
            </div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-white leading-tight mb-6">
              Imprevistos acontecem.<br />
              <span className="text-blue-100">As aulas podem continuar.</span>
            </h1>
            <p className="text-blue-100 text-lg md:text-xl leading-relaxed mb-10 max-w-2xl">
              O AulaSempre conecta escolas e faculdades privadas a professores qualificados e disponíveis para substituições temporárias — em minutos, não em horas.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <button
                onClick={() => navigate("/demo?perfil=instituicao")}
                className="bg-white text-blue-700 font-bold px-8 py-4 rounded-xl hover:bg-blue-50 transition-all shadow-lg text-base"
              >
                Sou uma instituição
              </button>
              <button
                onClick={() => navigate("/demo?perfil=professor")}
                className="bg-blue-500/40 border-2 border-white/40 text-white font-bold px-8 py-4 rounded-xl hover:bg-blue-500/60 transition-all text-base"
              >
                Sou professor
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* Como funciona */}
      <section className="py-20 bg-slate-50">
        <div className="max-w-6xl mx-auto px-6">
          <div className="text-center mb-14">
            <h2 className="text-3xl font-bold text-slate-800 mb-3">Como funciona</h2>
            <p className="text-slate-500 max-w-xl mx-auto">
              Em três etapas simples, a escola resolve uma ausência inesperada e o professor encontra uma oportunidade.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {steps.map((s) => (
              <div key={s.num} className="bg-white rounded-2xl p-8 border border-slate-100 shadow-sm relative">
                <div className="w-10 h-10 bg-blue-600 text-white rounded-xl flex items-center justify-center font-bold text-lg mb-5">
                  {s.num}
                </div>
                <div className="text-3xl mb-4">{s.icon}</div>
                <h3 className="text-lg font-bold text-slate-800 mb-3">{s.title}</h3>
                <p className="text-slate-500 text-sm leading-relaxed">{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Benefícios */}
      <section className="py-20 bg-white">
        <div className="max-w-6xl mx-auto px-6">
          <div className="text-center mb-14">
            <h2 className="text-3xl font-bold text-slate-800 mb-3">Para quem é o AulaSempre</h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {/* Instituição */}
            <div className="bg-blue-50 border border-blue-100 rounded-2xl p-8">
              <div className="flex items-center gap-3 mb-6">
                <div className="w-12 h-12 bg-blue-600 rounded-xl flex items-center justify-center text-2xl">🏫</div>
                <div>
                  <h3 className="text-xl font-bold text-slate-800">Para instituições</h3>
                  <p className="text-sm text-slate-500">Escolas e faculdades privadas</p>
                </div>
              </div>
              <ul className="space-y-3 mb-8">
                {institutionBenefits.map((b) => (
                  <li key={b} className="flex items-start gap-3">
                    <span className="text-blue-600 font-bold mt-0.5">✓</span>
                    <span className="text-slate-700 text-sm">{b}</span>
                  </li>
                ))}
              </ul>
              <button
                onClick={() => navigate("/demo?perfil=instituicao")}
                className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 rounded-xl transition-all text-sm"
              >
                Sou uma instituição →
              </button>
            </div>

            {/* Professor */}
            <div className="bg-green-50 border border-green-100 rounded-2xl p-8">
              <div className="flex items-center gap-3 mb-6">
                <div className="w-12 h-12 bg-green-600 rounded-xl flex items-center justify-center text-2xl">👩‍🏫</div>
                <div>
                  <h3 className="text-xl font-bold text-slate-800">Para professores</h3>
                  <p className="text-sm text-slate-500">Licenciados disponíveis para substituições</p>
                </div>
              </div>
              <ul className="space-y-3 mb-8">
                {teacherBenefits.map((b) => (
                  <li key={b} className="flex items-start gap-3">
                    <span className="text-green-600 font-bold mt-0.5">✓</span>
                    <span className="text-slate-700 text-sm">{b}</span>
                  </li>
                ))}
              </ul>
              <button
                onClick={() => navigate("/demo?perfil=professor")}
                className="w-full bg-green-600 hover:bg-green-700 text-white font-semibold py-3 rounded-xl transition-all text-sm"
              >
                Sou professor →
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* CTA final */}
      <section className="py-20 bg-blue-700">
        <div className="max-w-2xl mx-auto px-6 text-center">
          <h2 className="text-3xl font-bold text-white mb-4">Explore a demonstração completa</h2>
          <p className="text-blue-100 mb-8 text-lg">
            Sem cadastro. Navegue pelo protótipo completo com dados de exemplo e veja o fluxo de ponta a ponta.
          </p>
          <button
            onClick={() => navigate("/demo")}
            className="bg-white text-blue-700 font-bold px-10 py-4 rounded-xl hover:bg-blue-50 transition-all shadow-lg text-base"
          >
            Experimentar demonstração
          </button>
          <p className="text-blue-200 text-xs mt-4">
            Dados fictícios. Nenhuma informação real é coletada.
          </p>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-slate-900 text-slate-400 py-10">
        <div className="max-w-6xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2.5">
            <div className="w-7 h-7 bg-blue-600 rounded-lg flex items-center justify-center">
              <svg width="14" height="14" viewBox="0 0 18 18" fill="none">
                <path d="M9 1.5L15.5 5.25V12.75L9 16.5L2.5 12.75V5.25L9 1.5Z" fill="white" />
              </svg>
            </div>
            <span className="font-bold text-white">
              Aula<span className="text-blue-400">Sempre</span>
            </span>
          </div>
          <p className="text-sm">
            Protótipo acadêmico — versão de demonstração. Não há serviço real em operação.
          </p>
          <div className="flex gap-6 text-sm">
            <button onClick={() => navigate("/demo?perfil=instituicao")} className="hover:text-white transition-colors">Sou instituição</button>
            <button onClick={() => navigate("/demo?perfil=professor")} className="hover:text-white transition-colors">Sou professor</button>
          </div>
        </div>
      </footer>
    </div>
  );
}

// Front-end/src/app/features/public/landing-page/landing-page.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';

@Component({
  selector: 'app-landing-page',
  standalone: true,
  imports: [CommonModule],
  template: `
<div class="landing">

  <!-- Nav -->
  <nav class="landing-nav">
    <div class="landing-nav__inner">
      <div class="logo">
        <div class="logo__icon">
          <svg width="18" height="18" viewBox="0 0 18 18" fill="none">
            <path d="M9 1.5L15.5 5.25V12.75L9 16.5L2.5 12.75V5.25L9 1.5Z" fill="white"/>
            <path d="M6 9L8.5 11.5L12.5 7" stroke="#2563EB" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
        </div>
        <span class="logo__text">Aula<span class="logo__accent">Sempre</span></span>
      </div>
      <div class="landing-nav__actions">
        <button class="btn btn--ghost" (click)="go('/entrar')">Entrar</button>
        <button class="btn btn--primary" (click)="go('/demo')">Experimentar demonstração</button>
      </div>
    </div>
  </nav>

  <!-- Hero -->
  <section class="hero">
    <div class="hero__grid-bg" aria-hidden="true"></div>
    <div class="hero__inner">
      <div class="hero__badge">
        <span class="hero__badge-dot"></span>
        Plataforma de substituição para escolas privadas
      </div>
      <h1 class="hero__title">
        Imprevistos acontecem.<br>
        <span class="hero__title-light">As aulas podem continuar.</span>
      </h1>
      <p class="hero__desc">
        O AulaSempre conecta escolas e faculdades privadas a professores qualificados
        e disponíveis para substituições temporárias — em minutos, não em horas.
      </p>
      <div class="hero__actions">
        <button class="btn hero__btn-inst" (click)="go('/demo?perfil=instituicao')">Sou uma instituição</button>
        <button class="btn hero__btn-prof" (click)="go('/demo?perfil=professor')">Sou professor</button>
      </div>
    </div>
  </section>

  <!-- Como funciona -->
  <section class="section section--gray">
    <div class="section__inner">
      <div class="section__header">
        <h2 class="section__title">Como funciona</h2>
        <p class="section__desc">Em três etapas simples, a escola resolve uma ausência inesperada e o professor encontra uma oportunidade.</p>
      </div>
      <div class="steps-grid">
        <div class="step-card" *ngFor="let s of steps">
          <div class="step-card__num">{{s.num}}</div>
          <div class="step-card__icon">{{s.icon}}</div>
          <h3 class="step-card__title">{{s.title}}</h3>
          <p class="step-card__desc">{{s.desc}}</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Benefícios -->
  <section class="section">
    <div class="section__inner">
      <div class="section__header">
        <h2 class="section__title">Para quem é o AulaSempre</h2>
      </div>
      <div class="benefits-grid">
        <!-- Instituição -->
        <div class="benefit-card benefit-card--blue">
          <div class="benefit-card__header">
            <div class="benefit-card__icon">🏫</div>
            <div>
              <h3 class="benefit-card__title">Para instituições</h3>
              <p class="benefit-card__sub">Escolas e faculdades privadas</p>
            </div>
          </div>
          <ul class="benefit-list">
            <li *ngFor="let b of institutionBenefits" class="benefit-list__item">
              <span class="benefit-list__check benefit-list__check--blue">✓</span>
              <span>{{b}}</span>
            </li>
          </ul>
          <button class="btn btn--primary btn--block" (click)="go('/demo?perfil=instituicao')">Sou uma instituição →</button>
        </div>

        <!-- Professor -->
        <div class="benefit-card benefit-card--green">
          <div class="benefit-card__header">
            <div class="benefit-card__icon benefit-card__icon--green">👩‍🏫</div>
            <div>
              <h3 class="benefit-card__title">Para professores</h3>
              <p class="benefit-card__sub">Licenciados disponíveis para substituições</p>
            </div>
          </div>
          <ul class="benefit-list">
            <li *ngFor="let b of teacherBenefits" class="benefit-list__item">
              <span class="benefit-list__check benefit-list__check--green">✓</span>
              <span>{{b}}</span>
            </li>
          </ul>
          <button class="btn btn--success btn--block" (click)="go('/demo?perfil=professor')">Sou professor →</button>
        </div>
      </div>
    </div>
  </section>

  <!-- CTA -->
  <section class="cta-section">
    <div class="cta-section__inner">
      <h2 class="cta-section__title">Explore a demonstração completa</h2>
      <p class="cta-section__desc">Sem cadastro. Navegue pelo protótipo completo com dados de exemplo e veja o fluxo de ponta a ponta.</p>
      <button class="btn cta-section__btn" (click)="go('/demo')">Experimentar demonstração</button>
      <p class="cta-section__note">Dados fictícios. Nenhuma informação real é coletada.</p>
    </div>
  </section>

  <!-- Footer -->
  <footer class="footer">
    <div class="footer__inner">
      <div class="logo">
        <div class="logo__icon">
          <svg width="14" height="14" viewBox="0 0 18 18" fill="none">
            <path d="M9 1.5L15.5 5.25V12.75L9 16.5L2.5 12.75V5.25L9 1.5Z" fill="white"/>
          </svg>
        </div>
        <span class="footer__logo-text">Aula<span class="footer__logo-accent">Sempre</span></span>
      </div>
      <p class="footer__copy">Protótipo acadêmico — versão de demonstração. Não há serviço real em operação.</p>
      <div class="footer__links">
        <button (click)="go('/demo?perfil=instituicao')">Sou instituição</button>
        <button (click)="go('/demo?perfil=professor')">Sou professor</button>
      </div>
    </div>
  </footer>

</div>
  `,
  styles: [`
    .landing { min-height: 100vh; background: #fff; }

    /* Nav */
    .landing-nav {
      position: sticky; top: 0; z-index: 40;
      background: rgba(255,255,255,.95); backdrop-filter: blur(12px);
      border-bottom: 1px solid #F1F5F9;
    }
    .landing-nav__inner {
      max-width: 1100px; margin: 0 auto; padding: 0 24px;
      height: 64px; display: flex; align-items: center; justify-content: space-between;
    }
    .landing-nav__actions { display: flex; align-items: center; gap: 10px; }

    /* Logo */
    .logo { display: flex; align-items: center; gap: 10px; }
    .logo__icon {
      width: 36px; height: 36px; background: #2563EB;
      border-radius: 10px; display: flex; align-items: center; justify-content: center;
      box-shadow: 0 2px 8px rgba(37,99,235,.3);
    }
    .logo__text { font-size: 18px; font-weight: 700; color: #0F172A; }
    .logo__accent { color: #2563EB; }

    /* Hero */
    .hero {
      background: linear-gradient(135deg, #1E40AF 0%, #2563EB 50%, #3B82F6 100%);
      position: relative; overflow: hidden;
    }
    .hero__grid-bg {
      position: absolute; inset: 0; opacity: .08;
      background-image: linear-gradient(rgba(255,255,255,.5) 1px, transparent 1px),
                        linear-gradient(90deg, rgba(255,255,255,.5) 1px, transparent 1px);
      background-size: 48px 48px;
    }
    .hero__inner {
      max-width: 1100px; margin: 0 auto; padding: 96px 24px;
      position: relative; z-index: 1;
    }
    .hero__badge {
      display: inline-flex; align-items: center; gap: 8px;
      background: rgba(255,255,255,.15); color: #fff;
      font-size: 13px; font-weight: 500; padding: 8px 16px;
      border-radius: 9999px; border: 1px solid rgba(255,255,255,.2);
      margin-bottom: 28px;
    }
    .hero__badge-dot {
      width: 8px; height: 8px; background: #4ADE80;
      border-radius: 50%; animation: pulse 2s infinite;
    }
    @keyframes pulse {
      0%,100% { opacity: 1; } 50% { opacity: .5; }
    }
    .hero__title {
      font-size: clamp(36px, 5vw, 60px); font-weight: 800;
      color: #fff; line-height: 1.15; margin-bottom: 20px;
    }
    .hero__title-light { color: #BFDBFE; }
    .hero__desc {
      font-size: 18px; color: #BFDBFE; max-width: 600px;
      line-height: 1.6; margin-bottom: 36px;
    }
    .hero__actions { display: flex; gap: 14px; flex-wrap: wrap; }
    .hero__btn-inst {
      background: #fff; color: #1D4ED8; font-weight: 700;
      padding: 14px 28px; border-radius: 12px; font-size: 15px;
      box-shadow: 0 4px 14px rgba(0,0,0,.15);
      &:hover { background: #EFF6FF; }
    }
    .hero__btn-prof {
      background: rgba(255,255,255,.15); color: #fff; font-weight: 700;
      border: 2px solid rgba(255,255,255,.35); padding: 14px 28px;
      border-radius: 12px; font-size: 15px;
      &:hover { background: rgba(255,255,255,.25); }
    }

    /* Sections */
    .section { padding: 80px 0; }
    .section--gray { background: #F8FAFC; }
    .section__inner { max-width: 1100px; margin: 0 auto; padding: 0 24px; }
    .section__header { text-align: center; margin-bottom: 48px; }
    .section__title { font-size: 32px; font-weight: 700; color: #0F172A; margin-bottom: 10px; }
    .section__desc { color: #64748B; max-width: 480px; margin: 0 auto; font-size: 15px; }

    /* Steps */
    .steps-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 20px; }
    .step-card {
      background: #fff; border: 1px solid #E2E8F0;
      border-radius: 20px; padding: 32px; box-shadow: 0 1px 4px rgba(0,0,0,.05);
      transition: box-shadow .2s, transform .2s;
      &:hover { box-shadow: 0 8px 24px rgba(0,0,0,.08); transform: translateY(-2px); }
    }
    .step-card__num {
      width: 40px; height: 40px; background: #2563EB; color: #fff;
      border-radius: 12px; display: flex; align-items: center; justify-content: center;
      font-weight: 700; font-size: 18px; margin-bottom: 16px;
    }
    .step-card__icon { font-size: 32px; margin-bottom: 12px; }
    .step-card__title { font-size: 17px; font-weight: 700; color: #0F172A; margin-bottom: 8px; }
    .step-card__desc { font-size: 14px; color: #64748B; line-height: 1.6; }

    /* Benefits */
    .benefits-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 24px; }
    .benefit-card {
      border-radius: 20px; padding: 32px;
      &--blue { background: #EFF6FF; border: 1px solid #BFDBFE; }
      &--green { background: #F0FDF4; border: 1px solid #BBF7D0; }
    }
    .benefit-card__header { display: flex; align-items: center; gap: 14px; margin-bottom: 24px; }
    .benefit-card__icon {
      width: 52px; height: 52px; background: #2563EB;
      border-radius: 14px; display: flex; align-items: center; justify-content: center;
      font-size: 24px; flex-shrink: 0;
      &--green { background: #16A34A; }
    }
    .benefit-card__title { font-size: 18px; font-weight: 700; color: #0F172A; }
    .benefit-card__sub { font-size: 13px; color: #64748B; margin-top: 2px; }
    .benefit-list { list-style: none; margin-bottom: 24px; display: flex; flex-direction: column; gap: 10px; }
    .benefit-list__item { display: flex; align-items: flex-start; gap: 10px; font-size: 14px; color: #334155; }
    .benefit-list__check { font-weight: 700; margin-top: 1px;
      &--blue { color: #2563EB; }
      &--green { color: #16A34A; }
    }

    /* CTA */
    .cta-section { background: #1E40AF; padding: 80px 0; }
    .cta-section__inner { max-width: 680px; margin: 0 auto; padding: 0 24px; text-align: center; }
    .cta-section__title { font-size: 32px; font-weight: 700; color: #fff; margin-bottom: 14px; }
    .cta-section__desc { font-size: 17px; color: #BFDBFE; margin-bottom: 32px; line-height: 1.6; }
    .cta-section__btn {
      background: #fff; color: #1D4ED8; font-weight: 700;
      font-size: 16px; padding: 16px 36px; border-radius: 14px;
      box-shadow: 0 4px 14px rgba(0,0,0,.2);
      &:hover { background: #EFF6FF; }
    }
    .cta-section__note { font-size: 12px; color: #93C5FD; margin-top: 14px; }

    /* Footer */
    .footer { background: #0F172A; padding: 40px 0; }
    .footer__inner {
      max-width: 1100px; margin: 0 auto; padding: 0 24px;
      display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: 16px;
    }
    .footer__logo-text { font-size: 16px; font-weight: 700; color: #fff; }
    .footer__logo-accent { color: #60A5FA; }
    .footer__copy { font-size: 13px; color: #64748B; }
    .footer__links {
      display: flex; gap: 24px;
      button { font-size: 13px; color: #64748B; &:hover { color: #fff; } transition: color .15s; }
    }
  `],
})
export class LandingPageComponent {
  constructor(private router: Router) {}

  go(path: string) { this.router.navigateByUrl(path); }

  steps = [
    { num: '1', icon: '📋', title: 'Solicite a substituição', desc: 'Informe disciplina, data, horário e nível de ensino. O sistema notifica professores disponíveis na sua região.' },
    { num: '2', icon: '🔍', title: 'Encontre o professor ideal', desc: 'Veja perfis verificados, avaliações de outras escolas, experiência e compatibilidade com a sua necessidade.' },
    { num: '3', icon: '✅', title: 'Confirme e acompanhe', desc: 'Envie o convite, receba a confirmação e acompanhe tudo pelo painel. Professor e escola recebem todos os detalhes.' },
  ];

  institutionBenefits = [
    'Professores disponíveis na sua cidade',
    'Perfis verificados com avaliações reais',
    'Fluxo rápido — solicitação em menos de 3 minutos',
    'Histórico e avaliações de todas as substituições',
    'Sem cancelamento de aulas por falta de professor',
  ];

  teacherBenefits = [
    'Receba convites para substituições próximas a você',
    'Escolha aceitar ou recusar cada convite',
    'Acumule avaliações e fortaleça seu perfil',
    'Flexibilidade de horário e modalidade',
    'Renda extra sem compromisso fixo',
  ];
}
